feat: Added a light version and an automatic (light/dark) version for…
pawroman/zola-theme-terminimal pull request #45
Opened 2023-06-16 18:38 UTC by lynnpepin

Thank you so much for your work here! I really love the Hugo Terminal theme, and I love the improvements you made, especially in removing the JavaScript.

This fork adds **light themes**, plus **light and dark** themes (which switch depending on user preference).  

Specifically:

 - Light-mode versions of each theme, e.g. `blue-light` or `orange-light`.
     - Light mode color accents are darker, and the logo text is now white instead of black.
 - Automatic light/dark versions of each theme, e.g. `blue-auto` or `orange-auto`.
     - This responds automatically by using the CSS media setting `prefers-color-scheme`. See https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Here's a screenshot of `blue-auto`, under light mode:

![Screenshot 2023-06-16 at 14 29 39](https://github.com/pawroman/zola-theme-terminimal/assets/19627675/436ae00c-b9d6-49af-bf21-dad4e4e2db21)

2023-06-21 20:53 UTC, pawroman requested changes
Hey, many thanks for the contribution! It's a cool little feature, especially for people who don't prefer dark color themes :+1:

The only remark I have code-wise is this: perhaps we could reduce the duplication between `color-auto.scss` (the dark version) and `color.scss` files somehow? It's essentially the same styles, but duplicated across 2 files, for each color. And that's not so great.

I'm not super familiar with [Zola's SCSS preprocessing capabilities](https://www.getzola.org/documentation/content/sass/) but perhaps you could find some way of including/inheriting the files. If not, don't worry -- just let me know and I'll merge as-is.

2023-06-21 20:53 UTC, pawroman commented on sass/color/green-auto.scss
> +    --border-color: rgba(0,0,16,.125)
Looks like a missing semicolon `;`

2023-06-21 22:13 UTC, lynnpepin commented
> Hey, many thanks for the contribution! It's a cool little feature, especially for people who don't prefer dark color themes 👍
> 
> The only remark I have code-wise is this: perhaps we could reduce the duplication between `color-auto.scss` (the dark version) and `color.scss` files somehow? It's essentially the same styles, but duplicated across 2 files, for each color. And that's not so great.
> 
> I'm not super familiar with [Zola's SCSS preprocessing capabilities](https://www.getzola.org/documentation/content/sass/) but perhaps you could find some way of including/inheriting the files. If not, don't worry -- just let me know and I'll merge as-is.

Sadly, I poked at this a bit when working on the PR, but I couldn't get it working. I don't know much about Zola's internals or how to take advantage of SCSS (compared to regular old CSS.)

But I'm sure it's possible, and I plan to keep using Terminimal for awhile. If I figure it out, I will submit another PR!

2023-06-22 07:54 UTC, pawroman commented
> Sadly, I poked at this a bit when working on the PR, but I couldn't get it working. I don't know much about Zola's internals or how to take advantage of SCSS (compared to regular old CSS.)

OK, that's fine. Let's address that one missing semicolon I spotted after writing the original reply.

I also gave the default "auto" setting some thought and I think it would be best to make it an opt-in feature for the time being, e.g. revert the default colors to what they were.

Rationale: With 250 stars, the theme seems to be getting quite popular (and I never expected this :sweat_smile:). I should really need to adopt some kind of release/versioning process and then such changes could be clearly communicated. Until then, I think it's best to avoid random breakage for our users.

2023-06-22 21:35 UTC, lynnpepin commented
Both were oversights on my part, thank you for pointing them out! 

I'm a big fan of the original and this adaptation. Congrats on the 250 stars! :)

2023-06-23 09:50 UTC, pawroman commented
Great stuff, thanks for the contribution!

2023-06-23 09:50 UTC, merged